[package]
name = "clmm_pool"
version = "0.0.1"
edition = "2021"

[dependencies]
soroban-sdk = { version = "23.1.0", default-features = false }

[dev-dependencies]
soroban-sdk = { version = "23.1.0", default-features = false, features = ["testutils"] }

[features]
testutils = []

